### ISSUE TITLE
Multiple primary key defined with `@Column(key = KeyType.PRIMARY, id = true)`

### ISSUE THREAD

**Issue by Tomyk9991** [JavaWebStack/ORM#39]
**Describe the Bug**
When defining a new model like this, where `Model` is just an abstract class in the same package

```
import lombok.Getter;
import lombok.Setter;
import org.javawebstack.orm.annotation.Column;
import org.javawebstack.orm.annotation.Dates;
import org.javawebstack.orm.annotation.SoftDelete;
import org.javawebstack.orm.util.KeyType;

import java.sql.Timestamp;

@Getter @Setter @Dates @SoftDelete
public class ApiToken extends Model {
    @Column(key = KeyType.PRIMARY, id = true)
    String apiToken;
    
    @Column
    String name;
    
    @Column
    Timestamp lastUsed;

    @Column
    Timestamp createdAt;
    @Column
    Timestamp updatedAt;
    @Column
    Timestamp deletedAt;
}
```
it produces a `Multiple primary key defined` exception

```
Exception in thread "main" org.javawebstack.orm.exception.ORMQueryException: Multiple primary key defined
	at org.javawebstack.orm.migration.AutoMigrator.migrateTable(AutoMigrator.java:109)
	at org.javawebstack.orm.migration.AutoMigrator.migrate(AutoMigrator.java:30)
	at org.javawebstack.orm.ORM.autoMigrate(ORM.java:71)
	at org.javawebstack.orm.ORM.autoMigrate(ORM.java:67)
```

**Comment by JanHolger** [comment]
Hi Thomas,

thank you for your issue report!

Unfortunately using the setup you described, I can't reproduce the issue.

```java
public class IssueTest {
    public static void main(String[] args) throws ORMConfigurationException {
        SQL sql = new MySQL("127.0.0.1", 3306, "issue_test", "issue_test", "issue_test");
        ORM.register(Model.class.getPackage(), sql, new ORMConfig()
                .setDefaultSize(255)
        );
        ORM.autoMigrate();
    }
}
```

```java
public abstract class Model extends org.javawebstack.orm.Model {

}
```

```java
@Getter
@Setter
@Dates
@SoftDelete
public class ApiToken extends Model {
    @Column(key = KeyType.PRIMARY, id = true)
    String apiToken;
    @Column
    String name;
    @Column
    Timestamp lastUsed;
    @Column
    Timestamp createdAt;
    @Column
    Timestamp updatedAt;
    @Column
    Timestamp deletedAt;
}
```

![image](https://user-images.githubusercontent.com/25184957/196483117-b6a40887-7129-4538-8eac-cc5cc54d4b8c.png)

![image](https://user-images.githubusercontent.com/25184957/196483217-a5bc11f9-e7e6-4103-bb51-9abb8c173993.png)

**Comment by x7airworker** [comment]
Closing this issue, because there is no activity anymore. My guess is he changed the primary key field name, but already had a table with a primary key in the database.
